BACKUP_FILE_POSTFIX = ".zfs"
CHECKSUM_FILE_POSTFIX = ".sha256"
EXPECTED_CHECKSUM_FILE_POSTFIX = ".expected_sha256"
INITIALIZED_FILE_NAME = ".initialized"
INITIAL_SNAPSHOT_POSTFIX = "initial"
SNAPSHOT_PREFIX_POSTFIX_SEPARATOR = "."
TARGET_SUBDIRECTORY = "zfs"

__all__ = [
    "BACKUP_FILE_POSTFIX",
    "CHECKSUM_FILE_POSTFIX",
    "EXPECTED_CHECKSUM_FILE_POSTFIX",
    "INITIALIZED_FILE_NAME",
    "INITIAL_SNAPSHOT_POSTFIX",
    "SNAPSHOT_PREFIX_POSTFIX_SEPARATOR",
    "TARGET_SUBDIRECTORY",
]
