BACKUP_FILE_POSTFIX = ".zfs"
EXPECTED_CHECKSUM_FILE_POSTFIX = ".sha256"
"""must be used in conjunction with the backup file postfix"""
CALCULATED_CHECKSUM_FILE_POSTFIX = ".calculated_sha256"
"""must be used in conjunction with the backup file postfix"""
INITIALIZED_FILE_NAME = ".initialized"
INITIAL_SNAPSHOT_POSTFIX = "initial"
SNAPSHOT_PREFIX_POSTFIX_SEPARATOR = "."
TARGET_STORAGE_SUBDIRECTORY = "zfs"
TARGET_DATASET_REPLACEMENT_POSTFIX = ".replacement"
REPLACED_ORIGINAL_DATASET_POSTFIX = ".replaced"

__all__ = [
    "BACKUP_FILE_POSTFIX",
    "EXPECTED_CHECKSUM_FILE_POSTFIX",
    "CALCULATED_CHECKSUM_FILE_POSTFIX",
    "INITIALIZED_FILE_NAME",
    "INITIAL_SNAPSHOT_POSTFIX",
    "SNAPSHOT_PREFIX_POSTFIX_SEPARATOR",
    "TARGET_STORAGE_SUBDIRECTORY",
    "TARGET_DATASET_REPLACEMENT_POSTFIX",
    "REPLACED_ORIGINAL_DATASET_POSTFIX",
]
